apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debug
  name: debug
  namespace: dev
spec:
  replicas: r12
  selector:
    matchLabels:
      app: debug
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debug
    spec:
      containers:
      - image: ghcr.io/wolcn/debug:1.0.0
        name: debug
        command:
          - sleep
          - infinity
        resources: {}
